# Generated by Django 4.2.1 on 2023-10-01 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_alter_robot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='model',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[0-9A-Z]{2}$', message='The sequence must contain uppercase characters')]),
        ),
        migrations.AlterField(
            model_name='robot',
            name='version',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[0-9A-Z]{2}$', message='The sequence must contain uppercase characters')]),
        ),
    ]
